# Source: k8up/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8up
  labels:
    helm.sh/chart: k8up-4.4.3
    app.kubernetes.io/name: k8up
    app.kubernetes.io/instance: k8up
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: k8up
      app.kubernetes.io/instance: k8up
  template:
    metadata:
      labels:
        app.kubernetes.io/name: k8up
        app.kubernetes.io/instance: k8up
    spec:
      securityContext:
        {}
      containers:
        - name: k8up-operator
          image: "ghcr.io/k8up-io/k8up:v2.7.2"
          imagePullPolicy: IfNotPresent
          args: [ operator ]
          env:
            - name: BACKUP_IMAGE
              value: "ghcr.io/k8up-io/k8up:v2.7.2"
            - name: TZ
              value: Europe/Paris
            - name: BACKUP_ENABLE_LEADER_ELECTION
              value: "true"
            - name: BACKUP_OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - name: http
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /metrics
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          securityContext:
            {}
          resources:
            limits:
              memory: 256Mi
            requests:
              cpu: 20m
              memory: 128Mi
      serviceAccountName: k8up