---
apiVersion: vinyl.solidite.fr/v1beta1
kind: Component
category: core
metadata:
  name: k8up
  description: Kubernetes Backup Operator
options:
  images:
    default:
      backup:
        registry: ghcr.io
        repository: k8up-io/k8up
        tag: v2.10.0
      operator:
        pullPolicy: IfNotPresent
        registry: ghcr.io
        repository: k8up-io/k8up
        tag: v2.10.0
    examples:
    - backup:
        registry: ghcr.io
        repository: k8up-io/k8up
        tag: v2.10.0
      operator:
        pullPolicy: IfNotPresent
        registry: ghcr.io
        repository: k8up-io/k8up
        tag: v2.10.0
    properties:
      backup:
        default:
          registry: ghcr.io
          repository: k8up-io/k8up
          tag: v2.10.0
        properties:
          registry:
            default: ghcr.io
            type: string
          repository:
            default: k8up-io/k8up
            type: string
          tag:
            default: v2.10.0
            type: string
        type: object
      operator:
        default:
          pullPolicy: IfNotPresent
          registry: ghcr.io
          repository: k8up-io/k8up
          tag: v2.10.0
        properties:
          pullPolicy:
            default: IfNotPresent
            type: string
          registry:
            default: ghcr.io
            type: string
          repository:
            default: k8up-io/k8up
            type: string
          tag:
            default: v2.10.0
            type: string
        type: object
    type: object
  resources:
    default:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 20m
        memory: 128Mi
    examples:
    - limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 20m
        memory: 128Mi
    properties:
      limits:
        default:
          cpu: 500m
          memory: 256Mi
        properties:
          cpu:
            default: 500m
            type: string
          memory:
            default: 256Mi
            type: string
        type: object
      requests:
        default:
          cpu: 20m
          memory: 128Mi
        properties:
          cpu:
            default: 20m
            type: string
          memory:
            default: 128Mi
            type: string
        type: object
    type: object
  timezone:
    default: Europe/Paris
    examples:
    - Europe/Paris
    type: string
dependencies:
- dist: null
  category: crd
  component: k8up
providers:
  kubernetes: null
  authentik: null
  kubectl: true
  postgresql: null
  mysql: null
  restapi: null
  http: null
  gitea: null
tfaddtype: null
