# Source: k8up/templates/executor-clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: 'k8up-executor'
  labels:
    helm.sh/chart: k8up-4.4.3
    app.kubernetes.io/name: k8up
    app.kubernetes.io/instance: k8up
    app.kubernetes.io/managed-by: Helm
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
  - apiGroups:
      - ""
    resources:
      - pods/exec
    verbs:
      - create
  - apiGroups:
      - k8up.io
    resources:
      - snapshots
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch