# Source: k8up/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8up
  labels:
    helm.sh/chart: k8up-4.3.0
    app.kubernetes.io/name: k8up
    app.kubernetes.io/instance: k8up
    app.kubernetes.io/managed-by: Helm