---
apiVersion: vinyl.solidite.fr/v1beta1
kind: Component
category: meta
metadata:
  name: core
  description: core meta-component installing all the core components
options:
  crds:
    default:
      cert-manager:
        enable: false
      flux:
        enable: false
      k8up:
        enable: false
      mariadb:
        enable: false
      mongo:
        enable: false
      pg:
        enable: false
      prometheus:
        enable: false
      rabbitmq:
        enable: false
      redis:
        enable: false
      secret-generator:
        enable: false
      traefik:
        enable: false
    examples:
    - cert-manager:
        enable: false
      flux:
        enable: false
      k8up:
        enable: false
      mariadb:
        enable: false
      mongo:
        enable: false
      pg:
        enable: false
      prometheus:
        enable: false
      rabbitmq:
        enable: false
      redis:
        enable: false
      secret-generator:
        enable: false
      traefik:
        enable: false
    properties:
      cert-manager:
        default:
          enable: false
        properties:
          enable:
            default: false
            type: boolean
        type: object
      flux:
        default:
          enable: false
        properties:
          enable:
            default: false
            type: boolean
        type: object
      k8up:
        default:
          enable: false
        properties:
          enable:
            default: false
            type: boolean
        type: object
      mariadb:
        default:
          enable: false
        properties:
          enable:
            default: false
            type: boolean
        type: object
      mongo:
        default:
          enable: false
        properties:
          enable:
            default: false
            type: boolean
        type: object
      pg:
        default:
          enable: false
        properties:
          enable:
            default: false
            type: boolean
        type: object
      prometheus:
        default:
          enable: false
        properties:
          enable:
            default: false
            type: boolean
        type: object
      rabbitmq:
        default:
          enable: false
        properties:
          enable:
            default: false
            type: boolean
        type: object
      redis:
        default:
          enable: false
        properties:
          enable:
            default: false
            type: boolean
        type: object
      secret-generator:
        default:
          enable: false
        properties:
          enable:
            default: false
            type: boolean
        type: object
      traefik:
        default:
          enable: false
        properties:
          enable:
            default: false
            type: boolean
        type: object
    type: object
  backup:
    default:
      k8up:
        enable: true
      namespace: vynil-backup
    examples:
    - k8up:
        enable: true
      namespace: vynil-backup
    properties:
      k8up:
        default:
          enable: true
        properties:
          enable:
            default: true
            type: boolean
        type: object
      namespace:
        default: vynil-backup
        type: string
    type: object
  security:
    default:
      cert-manager:
        enable: true
      letsencrypt:
        enable: false
      namespace: vynil-security
      secret-generator:
        enable: true
      self-sign:
        enable: false
    examples:
    - cert-manager:
        enable: true
      letsencrypt:
        enable: false
      namespace: vynil-security
      secret-generator:
        enable: true
      self-sign:
        enable: false
    properties:
      cert-manager:
        default:
          enable: true
        properties:
          enable:
            default: true
            type: boolean
        type: object
      letsencrypt:
        default:
          enable: false
        properties:
          enable:
            default: false
            type: boolean
        type: object
      namespace:
        default: vynil-security
        type: string
      secret-generator:
        default:
          enable: true
        properties:
          enable:
            default: true
            type: boolean
        type: object
      self-sign:
        default:
          enable: false
        properties:
          enable:
            default: false
            type: boolean
        type: object
    type: object
  traefik:
    default:
      enable: true
      namespace: traefik
    examples:
    - enable: true
      namespace: traefik
    properties:
      enable:
        default: true
        type: boolean
      namespace:
        default: traefik
        type: string
    type: object
  databases:
    default:
      mariadb:
        enable: false
      mongo:
        enable: false
      namespace: vynil-dbo
      pg:
        enable: true
      postgresql:
        enable: true
      rabbitmq:
        enable: false
      redis:
        enable: true
    examples:
    - mariadb:
        enable: false
      mongo:
        enable: false
      namespace: vynil-dbo
      pg:
        enable: true
      postgresql:
        enable: true
      rabbitmq:
        enable: false
      redis:
        enable: true
    properties:
      mariadb:
        default:
          enable: false
        properties:
          enable:
            default: false
            type: boolean
        type: object
      mongo:
        default:
          enable: false
        properties:
          enable:
            default: false
            type: boolean
        type: object
      namespace:
        default: vynil-dbo
        type: string
      pg:
        default:
          enable: true
        properties:
          enable:
            default: true
            type: boolean
        type: object
      postgresql:
        default:
          enable: true
        properties:
          enable:
            default: true
            type: boolean
        type: object
      rabbitmq:
        default:
          enable: false
        properties:
          enable:
            default: false
            type: boolean
        type: object
      redis:
        default:
          enable: true
        properties:
          enable:
            default: true
            type: boolean
        type: object
    type: object
  flux:
    default:
      enable: false
      namespace: flux
    examples:
    - enable: false
      namespace: flux
    properties:
      enable:
        default: false
        type: boolean
      namespace:
        default: flux
        type: string
    type: object
dependencies: []
providers:
  kubernetes: true
  authentik: null
  kubectl: true
  postgresql: null
  restapi: null
  http: null
tfaddtype: null
