---
apiVersion: vinyl.solidite.fr/v1beta1
kind: Component
category: meta
metadata:
  name: core
  description: core meta-component installing all the core components
options:
  flux:
    default:
      enable: false
      namespace: flux
    examples:
    - enable: false
      namespace: flux
    properties:
      enable:
        default: false
        type: boolean
      namespace:
        default: flux
        type: string
    type: object
  backup:
    default:
      k8up:
        enable: true
      namespace: vynil-backup
    examples:
    - k8up:
        enable: true
      namespace: vynil-backup
    properties:
      k8up:
        default:
          enable: true
        properties:
          enable:
            default: true
            type: boolean
        type: object
      namespace:
        default: vynil-backup
        type: string
    type: object
  crds:
    default:
      cert-manager:
        enable: false
      flux:
        enable: false
      jaeger:
        enable: false
      k8up:
        enable: false
      mariadb:
        enable: false
      mayfly:
        enable: false
      mongo:
        enable: false
      mysql:
        enable: false
      opentelemetry:
        enable: false
      pg:
        enable: false
      prometheus:
        enable: false
      rabbitmq:
        enable: false
      redis:
        enable: false
      secret-generator:
        enable: false
      tekton_pipelines:
        enable: false
      tekton_triggers:
        enable: false
      traefik:
        enable: false
    examples:
    - cert-manager:
        enable: false
      flux:
        enable: false
      jaeger:
        enable: false
      k8up:
        enable: false
      mariadb:
        enable: false
      mayfly:
        enable: false
      mongo:
        enable: false
      mysql:
        enable: false
      opentelemetry:
        enable: false
      pg:
        enable: false
      prometheus:
        enable: false
      rabbitmq:
        enable: false
      redis:
        enable: false
      secret-generator:
        enable: false
      tekton_pipelines:
        enable: false
      tekton_triggers:
        enable: false
      traefik:
        enable: false
    properties:
      cert-manager:
        default:
          enable: false
        properties:
          enable:
            default: false
            type: boolean
        type: object
      flux:
        default:
          enable: false
        properties:
          enable:
            default: false
            type: boolean
        type: object
      jaeger:
        default:
          enable: false
        properties:
          enable:
            default: false
            type: boolean
        type: object
      k8up:
        default:
          enable: false
        properties:
          enable:
            default: false
            type: boolean
        type: object
      mariadb:
        default:
          enable: false
        properties:
          enable:
            default: false
            type: boolean
        type: object
      mayfly:
        default:
          enable: false
        properties:
          enable:
            default: false
            type: boolean
        type: object
      mongo:
        default:
          enable: false
        properties:
          enable:
            default: false
            type: boolean
        type: object
      mysql:
        default:
          enable: false
        properties:
          enable:
            default: false
            type: boolean
        type: object
      opentelemetry:
        default:
          enable: false
        properties:
          enable:
            default: false
            type: boolean
        type: object
      pg:
        default:
          enable: false
        properties:
          enable:
            default: false
            type: boolean
        type: object
      prometheus:
        default:
          enable: false
        properties:
          enable:
            default: false
            type: boolean
        type: object
      rabbitmq:
        default:
          enable: false
        properties:
          enable:
            default: false
            type: boolean
        type: object
      redis:
        default:
          enable: false
        properties:
          enable:
            default: false
            type: boolean
        type: object
      secret-generator:
        default:
          enable: false
        properties:
          enable:
            default: false
            type: boolean
        type: object
      tekton_pipelines:
        default:
          enable: false
        properties:
          enable:
            default: false
            type: boolean
        type: object
      tekton_triggers:
        default:
          enable: false
        properties:
          enable:
            default: false
            type: boolean
        type: object
      traefik:
        default:
          enable: false
        properties:
          enable:
            default: false
            type: boolean
        type: object
    type: object
  security:
    default:
      cert-manager:
        enable: true
      letsencrypt:
        enable: false
      namespace: vynil-security
      secret-generator:
        enable: true
      self-sign:
        enable: false
    examples:
    - cert-manager:
        enable: true
      letsencrypt:
        enable: false
      namespace: vynil-security
      secret-generator:
        enable: true
      self-sign:
        enable: false
    properties:
      cert-manager:
        default:
          enable: true
        properties:
          enable:
            default: true
            type: boolean
        type: object
      letsencrypt:
        default:
          enable: false
        properties:
          enable:
            default: false
            type: boolean
        type: object
      namespace:
        default: vynil-security
        type: string
      secret-generator:
        default:
          enable: true
        properties:
          enable:
            default: true
            type: boolean
        type: object
      self-sign:
        default:
          enable: false
        properties:
          enable:
            default: false
            type: boolean
        type: object
    type: object
  traefik:
    default:
      enable: true
      namespace: traefik
    examples:
    - enable: true
      namespace: traefik
    properties:
      enable:
        default: true
        type: boolean
      namespace:
        default: traefik
        type: string
    type: object
  tools:
    default:
      jaeger:
        enable: false
      mayfly:
        enable: true
      metrics_server:
        enable: false
      namespace: vynil-tools
      node_problem_detector:
        enable: false
      opentelemetry:
        enable: false
      prometheus:
        enable: true
      reloader:
        enable: true
      tekton_pipelines:
        enable: false
      tekton_triggers:
        enable: false
    examples:
    - jaeger:
        enable: false
      mayfly:
        enable: true
      metrics_server:
        enable: false
      namespace: vynil-tools
      node_problem_detector:
        enable: false
      opentelemetry:
        enable: false
      prometheus:
        enable: true
      reloader:
        enable: true
      tekton_pipelines:
        enable: false
      tekton_triggers:
        enable: false
    properties:
      jaeger:
        default:
          enable: false
        properties:
          enable:
            default: false
            type: boolean
        type: object
      mayfly:
        default:
          enable: true
        properties:
          enable:
            default: true
            type: boolean
        type: object
      metrics_server:
        default:
          enable: false
        properties:
          enable:
            default: false
            type: boolean
        type: object
      namespace:
        default: vynil-tools
        type: string
      node_problem_detector:
        default:
          enable: false
        properties:
          enable:
            default: false
            type: boolean
        type: object
      opentelemetry:
        default:
          enable: false
        properties:
          enable:
            default: false
            type: boolean
        type: object
      prometheus:
        default:
          enable: true
        properties:
          enable:
            default: true
            type: boolean
        type: object
      reloader:
        default:
          enable: true
        properties:
          enable:
            default: true
            type: boolean
        type: object
      tekton_pipelines:
        default:
          enable: false
        properties:
          enable:
            default: false
            type: boolean
        type: object
      tekton_triggers:
        default:
          enable: false
        properties:
          enable:
            default: false
            type: boolean
        type: object
    type: object
  databases:
    default:
      mariadb:
        enable: false
      mongo:
        enable: true
      mysql:
        enable: false
      namespace: vynil-dbo
      ndb:
        enable: false
      pg:
        enable: true
      postgresql:
        enable: false
      rabbitmq:
        enable: false
      redis:
        enable: true
    examples:
    - mariadb:
        enable: false
      mongo:
        enable: true
      mysql:
        enable: false
      namespace: vynil-dbo
      ndb:
        enable: false
      pg:
        enable: true
      postgresql:
        enable: false
      rabbitmq:
        enable: false
      redis:
        enable: true
    properties:
      mariadb:
        default:
          enable: false
        properties:
          enable:
            default: false
            type: boolean
        type: object
      mongo:
        default:
          enable: true
        properties:
          enable:
            default: true
            type: boolean
        type: object
      mysql:
        default:
          enable: false
        properties:
          enable:
            default: false
            type: boolean
        type: object
      namespace:
        default: vynil-dbo
        type: string
      ndb:
        default:
          enable: false
        properties:
          enable:
            default: false
            type: boolean
        type: object
      pg:
        default:
          enable: true
        properties:
          enable:
            default: true
            type: boolean
        type: object
      postgresql:
        default:
          enable: false
        properties:
          enable:
            default: false
            type: boolean
        type: object
      rabbitmq:
        default:
          enable: false
        properties:
          enable:
            default: false
            type: boolean
        type: object
      redis:
        default:
          enable: true
        properties:
          enable:
            default: true
            type: boolean
        type: object
    type: object
dependencies: []
providers:
  kubernetes: true
  authentik: null
  kubectl: true
  postgresql: null
  mysql: null
  restapi: null
  http: null
  gitea: null
tfaddtype: null
