---
apiVersion: vinyl.solidite.fr/v1beta1
kind: Component
category: core
metadata:
  name: crd-traefik
  description: CRD for Traefik
options:
  release:
    default: 23.0.1
    examples:
    - 23.0.1
    type: string
dependencies: []
