apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    name: jaeger-operator
  name: jaeger-operator-serving-cert
  namespace: vinyl-monitor
spec:
  dnsNames:
  - jaeger-operator-webhook-service.vinyl-monitor.svc
  - jaeger-operator-webhook-service.vinyl-monitor.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: jaeger-operator-selfsigned-issuer
  secretName: jaeger-operator-service-cert
  subject:
    organizationalUnits:
    - jaeger-operator