---
apiVersion: vinyl.solidite.fr/v1beta1
kind: Component
category: core
metadata:
  name: jaeger
  description: null
options:
  replicas:
    default: 1
    examples:
    - 1
    type: integer
  images:
    default:
      operator:
        pullPolicy: IfNotPresent
        registry: quay.io
        repository: jaegertracing/jaeger-operator
        tag: 1.53.0
      rbac_proxy:
        pullPolicy: IfNotPresent
        registry: gcr.io
        repository: kubebuilder/kube-rbac-proxy
        tag: v0.13.1
    examples:
    - operator:
        pullPolicy: IfNotPresent
        registry: quay.io
        repository: jaegertracing/jaeger-operator
        tag: 1.53.0
      rbac_proxy:
        pullPolicy: IfNotPresent
        registry: gcr.io
        repository: kubebuilder/kube-rbac-proxy
        tag: v0.13.1
    properties:
      operator:
        default:
          pullPolicy: IfNotPresent
          registry: quay.io
          repository: jaegertracing/jaeger-operator
          tag: 1.53.0
        properties:
          pullPolicy:
            default: IfNotPresent
            enum:
            - Always
            - Never
            - IfNotPresent
            type: string
          registry:
            default: quay.io
            type: string
          repository:
            default: jaegertracing/jaeger-operator
            type: string
          tag:
            default: 1.53.0
            type: string
        type: object
      rbac_proxy:
        default:
          pullPolicy: IfNotPresent
          registry: gcr.io
          repository: kubebuilder/kube-rbac-proxy
          tag: v0.13.1
        properties:
          pullPolicy:
            default: IfNotPresent
            enum:
            - Always
            - Never
            - IfNotPresent
            type: string
          registry:
            default: gcr.io
            type: string
          repository:
            default: kubebuilder/kube-rbac-proxy
            type: string
          tag:
            default: v0.13.1
            type: string
        type: object
    type: object
dependencies:
- dist: null
  category: crd
  component: jaeger
providers:
  kubernetes: true
  authentik: null
  kubectl: true
  postgresql: null
  mysql: null
  restapi: null
  http: null
  gitea: null
tfaddtype: null
