apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    name: jaeger-operator
  name: leader-election-rolebinding
  namespace: vinyl-monitor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: leader-election-role
subjects:
- kind: ServiceAccount
  name: jaeger-operator
  namespace: vinyl-monitor