---
apiVersion: vinyl.solidite.fr/v1beta1
kind: Component
category: core
metadata:
  name: cert-manager
  description: |-
    Cloud native certificate management
    X.509 certificate management for Kubernetes
options:
  images:
    default:
      cainjector:
        registry: quay.io
        repository: jetstack/cert-manager-cainjector
        tag: v1.14.2
      controller:
        registry: quay.io
        repository: jetstack/cert-manager-controller
        tag: v1.14.2
      startupapicheck:
        registry: quay.io
        repository: jetstack/cert-manager-ctl
        tag: v1.14.2
      webhook:
        registry: quay.io
        repository: jetstack/cert-manager-webhook
        tag: v1.14.2
    examples:
    - cainjector:
        registry: quay.io
        repository: jetstack/cert-manager-cainjector
        tag: v1.14.2
      controller:
        registry: quay.io
        repository: jetstack/cert-manager-controller
        tag: v1.14.2
      startupapicheck:
        registry: quay.io
        repository: jetstack/cert-manager-ctl
        tag: v1.14.2
      webhook:
        registry: quay.io
        repository: jetstack/cert-manager-webhook
        tag: v1.14.2
    properties:
      cainjector:
        default:
          registry: quay.io
          repository: jetstack/cert-manager-cainjector
          tag: v1.14.2
        properties:
          registry:
            default: quay.io
            type: string
          repository:
            default: jetstack/cert-manager-cainjector
            type: string
          tag:
            default: v1.14.2
            type: string
        type: object
      controller:
        default:
          registry: quay.io
          repository: jetstack/cert-manager-controller
          tag: v1.14.2
        properties:
          registry:
            default: quay.io
            type: string
          repository:
            default: jetstack/cert-manager-controller
            type: string
          tag:
            default: v1.14.2
            type: string
        type: object
      startupapicheck:
        default:
          registry: quay.io
          repository: jetstack/cert-manager-ctl
          tag: v1.14.2
        properties:
          registry:
            default: quay.io
            type: string
          repository:
            default: jetstack/cert-manager-ctl
            type: string
          tag:
            default: v1.14.2
            type: string
        type: object
      webhook:
        default:
          registry: quay.io
          repository: jetstack/cert-manager-webhook
          tag: v1.14.2
        properties:
          registry:
            default: quay.io
            type: string
          repository:
            default: jetstack/cert-manager-webhook
            type: string
          tag:
            default: v1.14.2
            type: string
        type: object
    type: object
  release:
    default: 1.14.2
    description: cert-manager version to use
    examples:
    - 1.14.2
    type: string
dependencies:
- dist: null
  category: crd
  component: cert-manager
providers: null
tfaddtype: null
