---
apiVersion: vinyl.solidite.fr/v1beta1
kind: Component
category: core
metadata:
  name: vynil
  description: Vynil is a package manager for the kubernetes operating system
options:
  images:
    default:
      agent:
        pullPolicy: IfNotPresent
        registry: docker.io
        repository: sebt3/vynil-agent
        tag: 0.2.12
      operator:
        pullPolicy: IfNotPresent
        registry: docker.io
        repository: sebt3/vynil-operator
        tag: 0.2.12
    examples:
    - agent:
        pullPolicy: IfNotPresent
        registry: docker.io
        repository: sebt3/vynil-agent
        tag: 0.2.12
      operator:
        pullPolicy: IfNotPresent
        registry: docker.io
        repository: sebt3/vynil-operator
        tag: 0.2.12
    properties:
      agent:
        default:
          pullPolicy: IfNotPresent
          registry: docker.io
          repository: sebt3/vynil-agent
          tag: 0.2.12
        properties:
          pullPolicy:
            default: IfNotPresent
            enum:
            - Always
            - Never
            - IfNotPresent
            type: string
          registry:
            default: docker.io
            type: string
          repository:
            default: sebt3/vynil-agent
            type: string
          tag:
            default: 0.2.12
            description: vynil-agent version to use
            type: string
        type: object
      operator:
        default:
          pullPolicy: IfNotPresent
          registry: docker.io
          repository: sebt3/vynil-operator
          tag: 0.2.12
        properties:
          pullPolicy:
            default: IfNotPresent
            enum:
            - Always
            - Never
            - IfNotPresent
            type: string
          registry:
            default: docker.io
            type: string
          repository:
            default: sebt3/vynil-operator
            type: string
          tag:
            default: 0.2.12
            description: vynil-operator version to use
            type: string
        type: object
    type: object
  resources:
    default:
      requests:
        cpu: 50m
        memory: 256Mi
    examples:
    - requests:
        cpu: 50m
        memory: 256Mi
    properties:
      requests:
        default:
          cpu: 50m
          memory: 256Mi
        properties:
          cpu:
            default: 50m
            type: string
          memory:
            default: 256Mi
            type: string
        type: object
    type: object
dependencies: []
providers:
  kubernetes: null
  authentik: null
  kubectl: true
  postgresql: null
  mysql: null
  restapi: null
  http: null
  gitea: null
tfaddtype: null
