kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vynil-agent-cluster-admin
subjects:
- kind: ServiceAccount
  namespace: default
  name: vynil-agent
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io