kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vynil-agent-admin
subjects:
- kind: ServiceAccount
  namespace: default
  name: vynil-agent
roleRef:
  kind: ClusterRole
  name: admin-vynil
  apiGroup: rbac.authorization.k8s.io