kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vynil-controller-resources
  namespace: default
subjects:
- kind: ServiceAccount
  namespace: default
  name: vynil-controller
roleRef:
  kind: Role
  name: resources-vynil
  apiGroup: rbac.authorization.k8s.io