kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vynil-controller-resources
subjects:
- kind: ServiceAccount
  namespace: default
  name: vynil-controller
- kind: ServiceAccount
  namespace: default
  name: vynil-agent
roleRef:
  kind: ClusterRole
  name: resources-vynil
  apiGroup: rbac.authorization.k8s.io