kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: resources-vynil
rules:
- apiGroups: ["vynil.solidite.fr"]
  resources: ["installs", "installs/status"]
  verbs: ["get", "watch", "list", "patch"]
- apiGroups: ["vynil.solidite.fr"]
  resources: ["distribs", "distribs/status"]
  verbs: ["get", "watch", "list", "patch"]
- apiGroups: ["events.k8s.io"]
  resources: ["events"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["namespaces", "secrets", "services"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "list"]
- apiGroups: ["storage.k8s.io"]
  resources: ["csidrivers", "storageclasses"]
  verbs: ["get", "list"]