# Expose the http port of the service
apiVersion: v1
kind: Service
metadata:
  name: vynil-controller
  namespace: default
  labels:
    app: vynil-controller
spec:
  ports:
  - port: 80
    targetPort: 9000
    protocol: TCP
    name: http
  selector:
    app: vynil-controller