---
apiVersion: vinyl.solidite.fr/v1beta1
kind: Component
category: meta
metadata:
  name: domain-ci
  description: null
options:
  issuer:
    default: letsencrypt-prod
    examples:
    - letsencrypt-prod
    type: string
  ingress-class:
    default: traefik
    examples:
    - traefik
    type: string
  gitea:
    default:
      enable: true
    examples:
    - enable: true
    properties:
      enable:
        default: true
        type: boolean
    type: object
  domain:
    default: your-company
    examples:
    - your-company
    type: string
  domain-name:
    default: your_company.com
    examples:
    - your_company.com
    type: string
dependencies: []
providers: null
