# Source: redis-operator/templates/role-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: redis-operator
  labels:
    app.kubernetes.io/name : redis-operator
    helm.sh/chart : redis-operator-0.15.9
    app.kubernetes.io/managed-by : Helm
    app.kubernetes.io/instance : redis-operator
    app.kubernetes.io/version : 0.15.1
    app.kubernetes.io/component: role-binding
    app.kubernetes.io/part-of : redis-operator
subjects:
- kind: ServiceAccount
  name: redis-operator
  namespace: dbo-redis
roleRef:
  kind: ClusterRole
  name: redis-operator
  apiGroup: rbac.authorization.k8s.io