---
# Source: redis-operator/templates/service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis-operator
  namespace: dbo-redis
  labels:
    app.kubernetes.io/name : redis-operator
    helm.sh/chart : redis-operator-0.15.9
    app.kubernetes.io/managed-by : Helm
    app.kubernetes.io/instance : redis-operator
    app.kubernetes.io/version : 0.15.1
    app.kubernetes.io/component: service-account
    app.kubernetes.io/part-of : redis-operator