---
apiVersion: vinyl.solidite.fr/v1beta1
kind: Component
category: apps
metadata:
  name: traefik-ui
  description: Access to the Traefik UI
options:
  domain-name:
    default: your_company.com
    examples:
    - your_company.com
    type: string
  domain:
    default: your-company
    examples:
    - your-company
    type: string
  issuer:
    default: letsencrypt-prod
    examples:
    - letsencrypt-prod
    type: string
  sub-domain:
    default: traefik
    examples:
    - traefik
    type: string
  ingress-class:
    default: traefik
    examples:
    - traefik
    type: string
dependencies:
- dist: null
  category: share
  component: authentik-forward
providers:
  kubernetes: true
  authentik: true
  kubectl: true
  postgresql: null
  restapi: true
  http: true
