---
apiVersion: vinyl.solidite.fr/v1beta1
kind: Component
category: meta
metadata:
  name: domain
  description: null
options:
  domain-name:
    default: your_company.com
    examples:
    - your_company.com
    type: string
  issuer:
    default: letsencrypt-prod
    examples:
    - letsencrypt-prod
    type: string
  ingress-class:
    default: traefik
    examples:
    - traefik
    type: string
  auth:
    default:
      enable: true
    examples:
    - enable: true
    properties:
      enable:
        default: true
        type: boolean
    type: object
  infra:
    default:
      enable: false
      traefik:
        enable: false
    examples:
    - enable: false
      traefik:
        enable: false
    properties:
      enable:
        default: false
        type: boolean
      traefik:
        default:
          enable: false
        properties:
          enable:
            default: false
            type: boolean
        type: object
    type: object
  ci:
    default:
      enable: false
      gitea:
        enable: true
    examples:
    - enable: false
      gitea:
        enable: true
    properties:
      enable:
        default: false
        type: boolean
      gitea:
        default:
          enable: true
        properties:
          enable:
            default: true
            type: boolean
        type: object
    type: object
dependencies: []
providers:
  kubernetes: null
  authentik: null
  kubectl: true
  postgresql: null
  restapi: null
  http: null
