---
apiVersion: vinyl.solidite.fr/v1beta1
kind: Component
category: meta
metadata:
  name: domain
  description: null
options:
  auth:
    default:
      enable: true
    examples:
    - enable: true
    properties:
      enable:
        default: true
        type: boolean
    type: object
  issuer:
    default: letsencrypt-prod
    examples:
    - letsencrypt-prod
    type: string
  infra:
    default:
      enable: false
    examples:
    - enable: false
    properties:
      enable:
        default: false
        type: boolean
    type: object
  ci:
    default:
      enable: false
    examples:
    - enable: false
    properties:
      enable:
        default: false
        type: boolean
    type: object
  domain-name:
    default: your_company.com
    examples:
    - your_company.com
    type: string
  ingress-class:
    default: traefik
    examples:
    - traefik
    type: string
dependencies: []
providers:
  kubernetes: null
  authentik: null
  kubectl: true
  postgresql: null
  restapi: null
  http: null
