---
apiVersion: vinyl.solidite.fr/v1beta1
kind: Component
category: meta
metadata:
  name: domain
  description: null
options:
  metas:
    default: []
    items:
      type: object
    type: array
  domain-name:
    default: your_company.com
    examples:
    - your_company.com
    type: string
  default-dist:
    default: core
    examples:
    - core
    type: string
dependencies: []
providers:
  kubernetes: true
  authentik: null
  kubectl: null
  postgresql: null
