---
apiVersion: vinyl.solidite.fr/v1beta1
kind: Component
category: meta
metadata:
  name: domain-infra
  description: null
options:
  domain:
    default: your-company
    examples:
    - your-company
    type: string
  domain-name:
    default: your_company.com
    examples:
    - your_company.com
    type: string
  issuer:
    default: letsencrypt-prod
    examples:
    - letsencrypt-prod
    type: string
  traefik:
    default:
      enable: false
    examples:
    - enable: false
    properties:
      enable:
        default: false
        type: boolean
    type: object
  ingress-class:
    default: traefik
    examples:
    - traefik
    type: string
dependencies: []
providers:
  kubernetes: true
  authentik: null
  kubectl: true
  postgresql: null
  restapi: null
  http: null
