# Source: authentik/templates/server-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentik-server
  labels:
    helm.sh/chart: authentik-2023.6.3
    app.kubernetes.io/name: authentik
    app.kubernetes.io/instance: authentik
    app.kubernetes.io/version: "2023.6.1"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: "server"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: authentik
      app.kubernetes.io/instance: authentik
      app.kubernetes.io/component: "server"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: authentik
        app.kubernetes.io/instance: authentik
        app.kubernetes.io/component: "server"
        app.kubernetes.io/version: "2023.6.1"
      annotations:
        goauthentik.io/config-checksum: 39339b4fd4c8511ca989fe40932e07b38befc9e3642eab092900cdde5cdf8f37
    spec:
      enableServiceLinks: true
      securityContext:
        {}
      containers:
        - name: authentik
          image: "ghcr.io/goauthentik/server:2023.6.1"
          imagePullPolicy: "IfNotPresent"
          args: ["server"]
          env:
          envFrom:
            - secretRef:
                name: authentik
          volumeMounts:
          ports:
            - name: http
              containerPort: 9000
              protocol: TCP
            - name: http-metrics
              containerPort: 9300
              protocol: TCP
            - name: https
              containerPort: 9443
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /-/health/live/
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          startupProbe:
            failureThreshold: 60
            httpGet:
              path: /-/health/live/
              port: http
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /-/health/ready/
              port: http
            periodSeconds: 10
          securityContext:
            {}
      volumes: