---
apiVersion: vinyl.solidite.fr/v1beta1
kind: Component
category: share
metadata:
  name: authentik
  description: authentik is an open-source Identity Provider focused on flexibility and versatility
options:
  admin:
    default:
      email: auth-admin
    examples:
    - email: auth-admin
    properties:
      email:
        default: auth-admin
        type: string
    type: object
  geoip:
    default: /geoip/GeoLite2-City.mmdb
    examples:
    - /geoip/GeoLite2-City.mmdb
    type: string
  email:
    default:
      port: 587
      timeout: 30
      use_ssl: false
      use_tls: false
    examples:
    - port: 587
      timeout: 30
      use_ssl: false
      use_tls: false
    properties:
      port:
        default: 587
        type: integer
      timeout:
        default: 30
        type: integer
      use_ssl:
        default: false
        type: boolean
      use_tls:
        default: false
        type: boolean
    type: object
  ingress-class:
    default: traefik
    examples:
    - traefik
    type: string
  error_reporting:
    default:
      enabled: false
      environment: k8s
      send_pii: false
    examples:
    - enabled: false
      environment: k8s
      send_pii: false
    properties:
      enabled:
        default: false
        type: boolean
      environment:
        default: k8s
        type: string
      send_pii:
        default: false
        type: boolean
    type: object
  issuer:
    default: letsencrypt-prod
    examples:
    - letsencrypt-prod
    type: string
  loglevel:
    default: info
    examples:
    - info
    type: string
  domain-name:
    default: your_company.com
    examples:
    - your_company.com
    type: string
  postgres:
    default:
      replicas: 1
      storage: 8Gi
      version: '14'
    examples:
    - replicas: 1
      storage: 8Gi
      version: '14'
    properties:
      replicas:
        default: 1
        type: integer
      storage:
        default: 8Gi
        type: string
      version:
        default: '14'
        type: string
    type: object
  redis:
    default:
      exporter:
        enabled: true
        image: quay.io/opstree/redis-exporter:v1.44.0
      image: quay.io/opstree/redis:v7.0.5
      storage: 8Gi
    examples:
    - exporter:
        enabled: true
        image: quay.io/opstree/redis-exporter:v1.44.0
      image: quay.io/opstree/redis:v7.0.5
      storage: 8Gi
    properties:
      exporter:
        default:
          enabled: true
          image: quay.io/opstree/redis-exporter:v1.44.0
        properties:
          enabled:
            default: true
            type: boolean
          image:
            default: quay.io/opstree/redis-exporter:v1.44.0
            type: string
        type: object
      image:
        default: quay.io/opstree/redis:v7.0.5
        type: string
      storage:
        default: 8Gi
        type: string
    type: object
  sub-domain:
    default: auth
    examples:
    - auth
    type: string
  image:
    default:
      project: goauthentik
      pullPolicy: IfNotPresent
      registry: ghcr.io
      repository: goauthentik/server
      tag: 2023.5.4
    examples:
    - project: goauthentik
      pullPolicy: IfNotPresent
      registry: ghcr.io
      repository: goauthentik/server
      tag: 2023.5.4
    properties:
      project:
        default: goauthentik
        type: string
      pullPolicy:
        default: IfNotPresent
        type: string
      registry:
        default: ghcr.io
        type: string
      repository:
        default: goauthentik/server
        type: string
      tag:
        default: 2023.5.4
        type: string
    type: object
  domain:
    default: your-company
    examples:
    - your-company
    type: string
dependencies:
- dist: null
  category: core
  component: cert-manager
- dist: null
  category: core
  component: secret-generator
- dist: null
  category: crd
  component: prometheus
- dist: null
  category: crd
  component: traefik
- dist: null
  category: dbo
  component: postgresql
- dist: null
  category: dbo
  component: redis
providers:
  kubernetes: null
  authentik: true
  kubectl: true
  postgresql: null
  mysql: null
  restapi: null
  http: null
  gitea: null
tfaddtype: null
