# Source: authentik/templates/prom-service-monitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: authentik
  labels:
    helm.sh/chart: authentik-2023.10.7
    app.kubernetes.io/name: authentik
    app.kubernetes.io/instance: authentik
    app.kubernetes.io/version: "2023.10.7"
    app.kubernetes.io/managed-by: Helm
spec:
  endpoints:
    - port: http-metrics
      scrapeTimeout: 3s
      interval: 30s
  selector:
    matchLabels:
      app.kubernetes.io/name: authentik
      app.kubernetes.io/instance: authentik