---
# Source: authentik/charts/serviceAccount/templates/service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: authentik
  namespace: vynil-auth
  labels:
    helm.sh/chart: serviceAccount-1.2.2
    app.kubernetes.io/name: authentik
    app.kubernetes.io/instance: authentik
    app.kubernetes.io/version: "2023.6.0"
    app.kubernetes.io/managed-by: Helm