---
apiVersion: vinyl.solidite.fr/v1beta1
kind: Component
category: crd
metadata:
  name: mongo
  description: CRD for the MongoDBCommunity operator
options:
  release:
    default: 0.9.0
    examples:
    - 0.9.0
    type: string
  apply:
    default: true
    examples:
    - true
    type: boolean
dependencies: []
providers: null
tfaddtype: null
