---
apiVersion: vinyl.solidite.fr/v1beta1
kind: Component
category: dbo
metadata:
  name: ndb
  description: Mysql-NDB operator
options:
  image:
    default:
      pull_policy: IfNotPresent
      registry: container-registry.oracle.com
      repository: mysql/community-ndb-operator
      tag: 8.4.0-1.4.0
    examples:
    - pull_policy: IfNotPresent
      registry: container-registry.oracle.com
      repository: mysql/community-ndb-operator
      tag: 8.4.0-1.4.0
    properties:
      properties:
        default: null
        pull_policy:
          enum:
          - Always
          - Never
          - IfNotPresent
      pull_policy:
        default: IfNotPresent
        type: string
      registry:
        default: container-registry.oracle.com
        type: string
      repository:
        default: mysql/community-ndb-operator
        type: string
      tag:
        default: 8.4.0-1.4.0
        type: string
    type: object
dependencies: []
providers:
  kubernetes: true
  authentik: null
  kubectl: true
  postgresql: null
  mysql: null
  restapi: null
  http: null
  gitea: null
tfaddtype: null
