# Source: ndb-operator/templates/rolebindings.yaml
# Ndb operator
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ndb-operator-crb
  namespace: vynil-dbo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ndb-operator-cr
subjects:
- kind: ServiceAccount
  name: ndb-operator-app-sa
  namespace: vynil-dbo