# Source: ndb-operator/templates/cluster-roles.yaml
# Cluster roles for Ndb Operator
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ndb-operator-cr
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs:
      - list
      - watch
      - delete

  - apiGroups: [""]
    resources: ["services"]
    verbs:
      - list
      - watch
      - create
      - patch
      - delete

  - apiGroups: [""]
    resources: ["configmaps"]
    verbs:
      - get
      - create
      - patch
      - list
      - watch

  - apiGroups: [""]
    resources: ["secrets"]
    verbs:
      - get
      - create
      - delete
      - list
      - watch

  - apiGroups: ["events.k8s.io"]
    resources: ["events"]
    verbs:
      - create
      - patch

  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs:
      - create
      - patch
      - list
      - watch
      - delete

  - apiGroups: ["policy"]
    resources: ["poddisruptionbudgets"]
    verbs:
      - list
      - watch
      - create

  - apiGroups: ["mysql.oracle.com"]
    resources:
      - ndbclusters
      - ndbclusters/status
    verbs:
      - get
      - list
      - patch
      - update
      - watch