---
apiVersion: vinyl.solidite.fr/v1beta1
kind: Component
category: core
metadata:
  name: mayfly
  description: null
options:
  image:
    default:
      pullPolicy: IfNotPresent
      registry: ghcr.io
      repository: stakater/reloader
      tag: v1.0.48
    examples:
    - pullPolicy: IfNotPresent
      registry: ghcr.io
      repository: stakater/reloader
      tag: v1.0.48
    properties:
      pullPolicy:
        default: IfNotPresent
        type: string
      registry:
        default: ghcr.io
        type: string
      repository:
        default: stakater/reloader
        type: string
      tag:
        default: v1.0.48
        type: string
    type: object
dependencies: []
providers: null
tfaddtype: null
